### ISSUE TITLE
Can't submit URL for indexing

### ISSUE THREAD

**Issue by TheRealCrusader** [ournews/our.news.public.issues.board#3]
https://www.sacbee.com/news/politics-government/capitol-alert/article238049454.html

I tried all types of settings on my browser, closed and re-opened browser. First time ever that I have not been able to add an article!
![Screenshot (702)](https://user-images.githubusercontent.com/58886261/70851534-33e13880-1e4b-11ea-9587-d1f0952d4278.png)

**Comment by rkzack** [comment]
@TheRealCrusader Sorry for the delay in responding, this was somehow overlooked. I've confirmed that there is something preventing this article from being imported, and will investigate further and update this issue with more details soon.

**Comment by rkzack** [comment]
It appears all imports from `sacbee.com` were failing. I switched the system to a tertiary import method for that domain, and imports are now working again. You should now be able to load the label on that article, and here's its specific landing page:

https://our.news/2020/05/03/new-california-law-redefines-who-gets-employment-benefits-the-lawsuits-are-just-starting/
